### ISSUE TITLE
Не собирается с ошибкой

### ISSUE THREAD

**Issue by vitlav** [lilans/Test-Project-For-Etersoft#1]
testformattnumber.o: In function `TestFormattNumber::TestFormattNumber(QObject*)':
testformattnumber.cpp:(.text+0x0): multiple definition of `TestFormattNumber::TestFormattNumber(QObject*)'
testformattnumber.o:testformattnumber.cpp:(.text+0x0): first defined here
testformattnumber.o: In function `TestFormattNumber::TestFormattNumber(QObject*)':
testformattnumber.cpp:(.text+0x0): multiple definition of `TestFormattNumber::TestFormattNumber(QObject*)'
testformattnumber.o:testformattnumber.cpp:(.text+0x0): first defined here

**Comment by lilans** [comment]
@vitlav, исправил
